all: prodcons-binsem prodcons-countsem 

prodcons-binsem: 
	gcc prodcons-binsem.c -o prodcons-binsem -lpthread
prodcons-countsem: 
	gcc prodcons-countsem.c -o prodcons-countsem -lpthread
clean:
	rm -f prodcons-binsem prodcons-countsem
